# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillow_retry', '0007_remove_pillowerror_queued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillowerror',
            name='current_attempt',
        ),
        migrations.RemoveField(
            model_name='pillowerror',
            name='date_next_attempt',
        ),
    ]
