# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 11:39
# flake8: noqa
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models
from corehq.sql_db.operations import RawSQLMigration


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0055_merge_20180719_1927'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TABLE public.icds_dashboard_ccs_record_thr_forms (
                state_id character varying(40) NOT NULL,
                month date NOT NULL,
                case_id character varying(40) NOT NULL,
                latest_time_end_processed timestamp with time zone NOT NULL,
                days_ration_given_mother smallint,
                CONSTRAINT icds_dashboard_ccs_record_thr_fo_days_ration_given_mother_check CHECK ((days_ration_given_mother >= 0))
            )  PARTITION BY LIST (month)
        """, state_operations=[
            migrations.CreateModel(
                name='AggregateCcsRecordTHRForms',
                fields=[
                    ('state_id', models.CharField(max_length=40)),
                    ('month', models.DateField(help_text='Will always be YYYY-MM-01')),
                    ('case_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                    ('latest_time_end_processed', models.DateTimeField(
                        help_text='The latest form.meta.timeEnd that has been processed for this case')),
                    ('days_ration_given_mother', models.PositiveSmallIntegerField(
                        help_text='Number of days the mother has been given rations this month', null=True)),
                ],
                options={
                    'db_table': 'icds_dashboard_ccs_record_thr_forms',
                },
            ),
        ]),
        migrations.RunSQL("""
            CREATE TABLE public.icds_dashboard_ccs_record_bp_forms (
                state_id character varying(40) NOT NULL,
                month date NOT NULL,
                case_id character varying(40) NOT NULL,
                latest_time_end_processed timestamp with time zone NOT NULL,
                immediate_breastfeeding smallint,
                anemia smallint,
                eating_extra smallint,
                resting smallint,
                anc_weight smallint,
                anc_blood_pressure smallint,
                bp_sys smallint,
                bp_dia smallint,
                anc_hemoglobin numeric(64,20),
                bleeding smallint,
                swelling smallint,
                blurred_vision smallint,
                convulsions smallint,
                rupture smallint,
                CONSTRAINT icds_dashboard_ccs_record_bp_form_immediate_breastfeeding_check CHECK ((immediate_breastfeeding >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_anc_blood_pressure_check CHECK ((anc_blood_pressure >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_anc_weight_check CHECK ((anc_weight >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_anemia_check CHECK ((anemia >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_bleeding_check CHECK ((bleeding >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_blurred_vision_check CHECK ((blurred_vision >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_bp_dia_check CHECK ((bp_dia >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_bp_sys_check CHECK ((bp_sys >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_convulsions_check CHECK ((convulsions >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_eating_extra_check CHECK ((eating_extra >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_resting_check CHECK ((resting >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_rupture_check CHECK ((rupture >= 0)),
                CONSTRAINT icds_dashboard_ccs_record_bp_forms_swelling_check CHECK ((swelling >= 0))
            ) PARTITION BY LIST (month)
        """, state_operations=[
            migrations.CreateModel(
                name='AggregateBirthPreparednesForms',
                fields=[
                    ('state_id', models.CharField(max_length=40)),
                    ('month', models.DateField(help_text='Will always be YYYY-MM-01')),
                    ('case_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                    ('latest_time_end_processed', models.DateTimeField(
                        help_text='The latest form.meta.timeEnd that has been processed for this case')),
                    ('immediate_breastfeeding', models.PositiveSmallIntegerField(
                        help_text="Has ever had /data/bp2/immediate_breastfeeding = 'yes'", null=True)),
                    ('anemia', models.PositiveSmallIntegerField(
                        help_text='Last value of /data/bp1/anemia. severe=1, moderate=2, normal=3', null=True)),
                    ('eating_extra',
                     models.PositiveSmallIntegerField(help_text="Last value of /data/bp1/eating_extra = 'yes'.",
                                                      null=True)),
                    ('resting',
                     models.PositiveSmallIntegerField(help_text="Last value of /data/bp1/resting = 'yes'.", null=True)),
                    ('anc_weight',
                     models.PositiveSmallIntegerField(help_text='Last value of anc_details/anc_weight', null=True)),
                    ('anc_blood_pressure', models.PositiveSmallIntegerField(
                        help_text='Last value of anc_details/anc_blood_pressure. normal=1, high=2, not_measured=3',
                        null=True)),
                    ('bp_sys',
                     models.PositiveSmallIntegerField(help_text='Last value of anc_details/bp_sys', null=True)),
                    ('bp_dia',
                     models.PositiveSmallIntegerField(help_text='Last value of anc_details/bp_dia', null=True)),
                    ('anc_hemoglobin',
                     models.DecimalField(decimal_places=20, help_text='Last value of anc_details/anc_hemoglobin',
                                         max_digits=64, null=True)),
                    ('bleeding',
                     models.PositiveSmallIntegerField(help_text="Last value of /data/bp2/bleeding = 'yes'", null=True)),
                    ('swelling',
                     models.PositiveSmallIntegerField(help_text="Last value of /data/bp2/swelling = 'yes'", null=True)),
                    ('blurred_vision',
                     models.PositiveSmallIntegerField(help_text="Last value of /data/bp2/blurred_vision = 'yes'",
                                                      null=True)),
                    ('convulsions',
                     models.PositiveSmallIntegerField(help_text="Last value of /data/bp2/convulsions = 'yes'",
                                                      null=True)),
                    ('rupture',
                     models.PositiveSmallIntegerField(help_text="Last value of /data/bp2/rupture = 'yes'", null=True)),
                ],
                options={
                    'db_table': 'icds_dashboard_ccs_record_bp_forms',
                },
            ),
        ]),
        migrations.RunSQL("""
            CREATE TABLE public.icds_dashboard_ccs_record_delivery_forms (
                state_id character varying(40) NOT NULL,
                month date NOT NULL,
                case_id character varying(40) NOT NULL,
                latest_time_end_processed timestamp with time zone NOT NULL,
                breastfed_at_birth smallint,
                CONSTRAINT icds_dashboard_ccs_record_delivery_for_breastfed_at_birth_check CHECK ((breastfed_at_birth >= 0))
            ) PARTITION BY LIST (month)
        """, state_operations=[
            migrations.CreateModel(
                name='AggregateCcsRecordDeliveryForms',
                fields=[
                    ('state_id', models.CharField(max_length=40)),
                    ('month', models.DateField(help_text='Will always be YYYY-MM-01')),
                    ('case_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                    ('latest_time_end_processed', models.DateTimeField(
                        help_text='The latest form.meta.timeEnd that has been processed for this case')),
                    ('breastfed_at_birth',
                     models.PositiveSmallIntegerField(help_text='whether any child was breastfed at birth', null=True)),
                ],
                options={
                    'db_table': 'icds_dashboard_ccs_record_delivery_forms',
                },
            ),
        ]),
        migrations.AlterModelOptions(
            name='aggregateccsrecordpostnatalcareforms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aggregatechildhealthpostnatalcareforms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aggregatechildhealththrforms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aggregatecomplementaryfeedingforms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aggregategrowthmonitoringforms',
            options={},
        ),
    ]
