# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-10 09:26
from __future__ import unicode_literals

from django.db import migrations, models


models_to_update = [
    'aggregateawcinfrastructureforms',
    'aggregatebirthpreparednesforms',
    'aggregateccsrecorddeliveryforms',
    'aggregateccsrecordpostnatalcareforms',
    'aggregateccsrecordthrforms',
    'aggregatechildhealthdailyfeedingforms',
    'aggregatechildhealthpostnatalcareforms',
    'aggregatechildhealththrforms',
    'aggregatecomplementaryfeedingforms',
    'aggregategrowthmonitoringforms',
]

def create_composite_primary_keys(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for model in models_to_update:
            model_cls = apps.get_model('icds_reports', model)
            pkey = '{}_pkey'.format(model_cls._meta.db_table)
            fields = list(model_cls._meta.unique_together)[0]
            columns = [model_cls._meta.get_field(field).column for field in fields]
            index = schema_editor._create_index_name(model_cls, columns, suffix="_uniq")
            cursor.execute("""
                CREATE UNIQUE INDEX {index} on "{table}" ({cols});
                ALTER TABLE "{table}" DROP CONSTRAINT {pkey},
                ADD CONSTRAINT {pkey} PRIMARY KEY USING INDEX {index};
            """.format(
                table=model_cls._meta.db_table,
                pkey=pkey,
                index=index,
                cols=','.join(columns)
            ))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0066_aggregatesqlprofile_last_included_doc_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregateawcinfrastructureforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregatebirthpreparednesforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateccsrecorddeliveryforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateccsrecordpostnatalcareforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateccsrecordthrforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregatechildhealthdailyfeedingforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregatechildhealthpostnatalcareforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregatechildhealththrforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregatecomplementaryfeedingforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregategrowthmonitoringforms',
            name='supervisor_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
