# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-10 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0067_add_supervisor_id_and_index'),
    ]

    operations = [
        migrations.RunSQL("""
            select create_distributed_table('icds_dashboard_comp_feed_form', 'supervisor_id');
            select create_distributed_table('icds_dashboard_ccs_record_postnatal_forms', 'supervisor_id');
            select create_distributed_table('icds_dashboard_child_health_postnatal_forms', 'supervisor_id');
            select create_distributed_table('icds_dashboard_child_health_thr_forms', 'supervisor_id');
            select create_distributed_table('icds_dashboard_ccs_record_thr_forms', 'supervisor_id');
            select create_distributed_table('icds_dashboard_ccs_record_bp_forms', 'supervisor_id');
            select create_distributed_table('icds_dashboard_ccs_record_delivery_forms', 'supervisor_id');
            select create_distributed_table('icds_dashboard_daily_feeding_forms', 'supervisor_id');
            select create_distributed_table('icds_dashboard_growth_monitoring_forms', 'supervisor_id');
            select create_distributed_table('icds_dashboard_infrastructure_forms', 'supervisor_id');
        """)

    ]
